FROM node:24.11.1-alpine3.22

WORKDIR /app

# Install bun
RUN npm install -g bun

# Copy package files
COPY package*.json ./
COPY bun.lockb ./

# Install dependencies
RUN bun install

# Copy source files
COPY . .

EXPOSE 8080

CMD ["bun", "run", "dev", "--host"]
